version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - test-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=test
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - test-network
    volumes:
      - .:/app
      - ./test_results:/app/test_results

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - API_URL=http://api:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - TEST_MODE=integration
    depends_on:
      - api
      - redis
    volumes:
      - .:/app
      - ./test_results:/app/test_results
    networks:
      - test-network
    command: pytest tests/integration --verbose --junitxml=/app/test_results/integration.xml

networks:
  test-network:
    driver: bridge